site_name: theSTART
nav:
  - Home: index.md
  - Setup(vazio):
      - Installation: installation.md
      - Configuration: config.md
  - Guides:
      - Pwnzilla: README.md
      - Pwnzilla INFO: HOW_IT_WORKS.md
  - About: about.md
theme:
  name: dracula
