site_name: theSTART
site_url: https://joaopef.github.io/theSTART/

nav:
  - Home: en/index.md
  - Setup:
      - Installation: en/installation.md
      - Configuration: en/config.md
  - Guides:
      - Pwnzilla: en/PwnZilla Guia.md
      - Pwnzilla INFO: en/1HOW_IT_WORKS.md
      - Self-Hosted Password Manager: en/Password Manager.md
  - About: en/about.md

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Português (PT)
      link: /pt/
      lang: pt
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/joaopef/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joaopefer/


extra_css:
  - styles.css

markdown_extensions:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

copyright: 
  "&copy; 2025 <a href='https://github.com/joaopef/' target='_blank' rel='noopener'>João Ferreira</a>"
