site_name: theSTART
site_url: https://joaopef.github.io/theSTART/
nav:
  - Home: index.md
  - Setup(vazio):
      - Installation: installation.md
      - Configuration: config.md
  - Guides:
      - Pwnzilla: PwnZilla Guia.md
      - Pwnzilla INFO: 1HOW_IT_WORKS.md
      - Self-Hosted Password Manager: Password Manager.md
  - About: about.md

theme:
  name: material  # Use the Dracula theme
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

 
extra_css:
  - styles.css  # Path to your custom styles.css (optional)

# Optional: Enable highlight.js for syntax highlighting
markdown_extensions:
  - codehilite:
      guess_lang: false  # Disable automatic guessing of code language
  - toc:
      permalink: true  # Enable table of contents
